// ─── Mock Data ────────────────────────────────────────────────────────────────
// Used when the backend API at localhost:8765 is unavailable.

const MOCK = {
  stats: {
    pending: 3,
    processed_today: 47,
    errors: 2,
  },

  pending: [
    {
      id: "pend-001",
      original_filename: "[SubsPlease] Dungeon Meshi - 24 (1080p).mkv",
      detected_title: "Delicious in Dungeon",
      season: 1,
      episode: 24,
      confidence: 0.96,
      mode: "auto",
      target_path: "/media/Anime/Delicious in Dungeon/Season 01/Delicious in Dungeon S01E24.mkv",
      status: "pending",
      source_size: "1.42 GB",
      detected_at: new Date(Date.now() - 4 * 60 * 1000).toISOString(),
    },
    {
      id: "pend-002",
      original_filename: "[Lilith-Raws] Mushoku Tensei II - 13.mkv",
      detected_title: "Mushoku Tensei",
      season: 2,
      episode: 13,
      confidence: 0.89,
      mode: "confirm",
      target_path: "/media/Anime/Mushoku Tensei/Season 02/Mushoku Tensei S02E13.mkv",
      status: "pending",
      source_size: "876 MB",
      detected_at: new Date(Date.now() - 12 * 60 * 1000).toISOString(),
    },
    {
      id: "pend-003",
      original_filename: "【极影】★04月新番 忘却Battery 第03话.mp4",
      detected_title: "忘却Battery",
      season: 1,
      episode: 3,
      confidence: 0.72,
      mode: "confirm",
      target_path: "/media/Anime/忘却Battery/Season 01/忘却Battery S01E03.mp4",
      status: "pending",
      source_size: "312 MB",
      detected_at: new Date(Date.now() - 28 * 60 * 1000).toISOString(),
    },
  ],

  recent: [
    {
      id: "act-001",
      filename: "[SubsPlease] Dungeon Meshi - 23 (1080p).mkv",
      title: "Delicious in Dungeon S01E23",
      status: "done",
      confidence: 0.97,
      mode: "auto",
      timestamp: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    },
    {
      id: "act-002",
      filename: "[Erai-raws] Frieren - 28 [1080p].mkv",
      title: "Frieren: Beyond Journey's End S01E28",
      status: "done",
      confidence: 0.94,
      mode: "auto",
      timestamp: new Date(Date.now() - 3.5 * 60 * 60 * 1000).toISOString(),
    },
    {
      id: "act-003",
      filename: "Oshi no Ko S2E04 [WEBRip].mkv",
      title: "Oshi no Ko S02E04",
      status: "done",
      confidence: 0.91,
      mode: "confirm",
      timestamp: new Date(Date.now() - 5 * 60 * 60 * 1000).toISOString(),
    },
    {
      id: "act-004",
      filename: "[DameDesuYo] Re_Zero - 02 (1920x1080).mkv",
      title: "Re:Zero S03E02",
      status: "error",
      confidence: 0.48,
      mode: "confirm",
      timestamp: new Date(Date.now() - 6 * 60 * 60 * 1000).toISOString(),
      error_msg: "Season detection failed — ambiguous release group tag",
    },
    {
      id: "act-005",
      filename: "[Yameii] Bocchi the Rock! - 13 [English Dub].mkv",
      title: "Bocchi the Rock! S01E13",
      status: "done",
      confidence: 0.93,
      mode: "auto",
      timestamp: new Date(Date.now() - 8 * 60 * 60 * 1000).toISOString(),
    },
  ],

  series: [
    {
      id: "ser-001",
      title: "Delicious in Dungeon",
      title_ja: "ダンジョン飯",
      mode: "auto",
      season_count: 1,
      episode_count: 24,
      last_activity: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
      folder: "/media/Anime/Delicious in Dungeon",
      status: "active",
    },
    {
      id: "ser-002",
      title: "Mushoku Tensei",
      title_ja: "無職転生",
      mode: "confirm",
      season_count: 2,
      episode_count: 36,
      last_activity: new Date(Date.now() - 12 * 60 * 1000).toISOString(),
      folder: "/media/Anime/Mushoku Tensei",
      status: "active",
    },
    {
      id: "ser-003",
      title: "忘却Battery",
      title_ja: "忘却Battery",
      mode: "confirm",
      season_count: 1,
      episode_count: 3,
      last_activity: new Date(Date.now() - 28 * 60 * 1000).toISOString(),
      folder: "/media/Anime/忘却Battery",
      status: "active",
    },
    {
      id: "ser-004",
      title: "Frieren: Beyond Journey's End",
      title_ja: "葬送のフリーレン",
      mode: "auto",
      season_count: 1,
      episode_count: 28,
      last_activity: new Date(Date.now() - 3.5 * 60 * 60 * 1000).toISOString(),
      folder: "/media/Anime/Frieren",
      status: "active",
    },
    {
      id: "ser-005",
      title: "Oshi no Ko",
      title_ja: "推しの子",
      mode: "confirm",
      season_count: 2,
      episode_count: 20,
      last_activity: new Date(Date.now() - 5 * 60 * 60 * 1000).toISOString(),
      folder: "/media/Anime/Oshi no Ko",
      status: "active",
    },
    {
      id: "ser-006",
      title: "Bocchi the Rock!",
      title_ja: "ぼっち・ざ・ろっく！",
      mode: "auto",
      season_count: 1,
      episode_count: 13,
      last_activity: new Date(Date.now() - 8 * 60 * 60 * 1000).toISOString(),
      folder: "/media/Anime/Bocchi the Rock",
      status: "complete",
    },
  ],

  logs: [
    {
      id: "log-001",
      original_filename: "[SubsPlease] Dungeon Meshi - 23 (1080p).mkv",
      renamed_to: "Delicious in Dungeon S01E23.mkv",
      status: "done",
      confidence: 0.97,
      mode: "auto",
      timestamp: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    },
    {
      id: "log-002",
      original_filename: "[Erai-raws] Frieren - 28 [1080p].mkv",
      renamed_to: "Frieren Beyond Journeys End S01E28.mkv",
      status: "done",
      confidence: 0.94,
      mode: "auto",
      timestamp: new Date(Date.now() - 3.5 * 60 * 60 * 1000).toISOString(),
    },
    {
      id: "log-003",
      original_filename: "Oshi no Ko S2E04 [WEBRip].mkv",
      renamed_to: "Oshi no Ko S02E04.mkv",
      status: "done",
      confidence: 0.91,
      mode: "confirm",
      timestamp: new Date(Date.now() - 5 * 60 * 60 * 1000).toISOString(),
    },
    {
      id: "log-004",
      original_filename: "[DameDesuYo] Re_Zero - 02 (1920x1080).mkv",
      renamed_to: null,
      status: "error",
      confidence: 0.48,
      mode: "confirm",
      timestamp: new Date(Date.now() - 6 * 60 * 60 * 1000).toISOString(),
      error_msg: "Season detection failed — ambiguous release group tag",
    },
    {
      id: "log-005",
      original_filename: "[Yameii] Bocchi the Rock! - 13 [English Dub].mkv",
      renamed_to: "Bocchi the Rock S01E13.mkv",
      status: "done",
      confidence: 0.93,
      mode: "auto",
      timestamp: new Date(Date.now() - 8 * 60 * 60 * 1000).toISOString(),
    },
    {
      id: "log-006",
      original_filename: "[SubsPlease] Dungeon Meshi - 22 (1080p).mkv",
      renamed_to: "Delicious in Dungeon S01E22.mkv",
      status: "done",
      confidence: 0.98,
      mode: "auto",
      timestamp: new Date(Date.now() - 26 * 60 * 60 * 1000).toISOString(),
    },
    {
      id: "log-007",
      original_filename: "[Lilith-Raws] Mushoku Tensei II - 12.mkv",
      renamed_to: "Mushoku Tensei S02E12.mkv",
      status: "done",
      confidence: 0.88,
      mode: "confirm",
      timestamp: new Date(Date.now() - 27 * 60 * 60 * 1000).toISOString(),
    },
    {
      id: "log-008",
      original_filename: "random_anime_ep05_720p.mkv",
      renamed_to: null,
      status: "skipped",
      confidence: 0.31,
      mode: "confirm",
      timestamp: new Date(Date.now() - 30 * 60 * 60 * 1000).toISOString(),
      error_msg: "Confidence too low — user skipped",
    },
  ],
};
